### ISSUE TITLE
Redirect has been blocked by CORS policy.

### ISSUE THREAD

**Issue by Runbo94** [Runbo94/gitgroup#1]
When I click the Auth button on the left top of the window. It will Send **GET http://localhost:8000/user/auth** to Gitgroup api server.
The handling method in the backend is 
```typescript
    this.router.use((req, res, next) => {
      res.header("Access-Control-Allow-Origin", "http://localhost:3000");
      res.header(
        "Access-Control-Allow-Headers",
        "Origin, X-Requested-With, Content-Type, Accept"
      );
      next();
    });

    //[method: get, url: /user/auth] - used to get the github authorization request page
    this.router.get("/", async (req: Request, res: Response) => {
      const auth: Authorization = new Authorization();
      return res.redirect(
        url.format({
          pathname: auth.getGithubAuthUrl(),
          query: {
            client_id: auth.getClientId()
          }
        })
      );
    });
```

The frontend shows the following error message:

```
Failed to load https://github.com/login/oauth/authorize?client_id=Iv1.6086bc7359ba9d0b: Redirect from 'https://github.com/login/oauth/authorize?client_id=Iv1.6086bc7359ba9d0b' to 'https://github.com/login?client_id=Iv1.6086bc7359ba9d0b&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3DIv1.6086bc7359ba9d0b' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. [http://localhost:3000/not-found]
Error: Network Error
createError.js:16
    at createError (c:\Users\runbo\Desktop\gitgroup\node_modules\axios\lib\core\createError.js:16:1)
    at XMLHttpRequest.handleError (c:\Users\runbo\Desktop\gitgroup\node_modules\axios\lib\adapters\xhr.js:87:1)
```

**Comment by Runbo94** [comment]
I choose to do redirection in the front end instead of in the backend. But I still don't know how to figure out this problem.
I tried to add some headers, it works for some other CORS policy problem, but it doesn't work for this problem. Maybe GitHub API doesn't allows this way to do redirect.
```
      res.header("Access-Control-Allow-Origin", "*");
      res.header(
        "Access-Control-Allow-Headers",
        "Origin, X-Requested-With, Content-Type, Accept, Authorization"
      );
```
